version: "3.8"

services:

  mariadb:
    image: mariadb:10.6
    working_dir: /application
    env_file: ./environment/mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  # Development
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MH_STORAGE: maildir
      MG_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

  # Development
  adminer:
    image: adminer
    ports:
      - 8001:8080
    depends_on:
      - mariadb

volumes:
  mariadb:
  maildir:
