version: "3.8"
services:

  mariadb:
    image: mariadb:10.6
    working_dir: /application
    volumes:
      - .:/application
    env_file: ./environment/mariadb.env
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8001:8080
    depends_on:
      - mariadb
